version: 2
updates:
- package-ecosystem: nuget
  directory: "/streamdeck-chatpager"
  schedule:
    interval: daily
  open-pull-requests-limit: 4
  ignore:
  - dependency-name: HtmlAgilityPack
    versions:
    - 1.11.30
    - 1.11.31
    - 1.11.32
  - dependency-name: TwitchLib.Api.Core
    versions:
    - 3.2.0
    - 3.2.1
    - 3.2.2
  - dependency-name: TwitchLib.Api
    versions:
    - 3.2.0
    - 3.2.1
    - 3.2.2
  - dependency-name: NLog
    versions:
    - 4.7.7
    - 4.7.8
  - dependency-name: TwitchLib.Client
    versions:
    - 3.2.0
    - 3.2.1
