//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatPager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAIAAABoJHXvAAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAGOWlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTAzLTI0VDIxOjAyOjMyLTA3OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjA" +
            "xOS0wMy0yNVQwMDoyNjo0My0wNzowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOS0wMy0yNVQwMDoyNjo" +
            "0My0wNzowMCIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHhtcE1" +
            "NOkluc3RhbmNlSUQ9InhtcC5paWQ6MTExNGIyNmMtZjU4Yy04NDRkLWE0YmEtZGJkM2E3ZDI3ZTJhIiB" +
            "4bXBNTTpEb2N1bWVudElEPSJhZG9iZTpkb2NpZDpwaG90b3Nob3A6Mzk5MmI4Y2EtM2MyNS0wMDRjLTk" +
            "2NjctMmM5NmU2YzMyMjU3IiB4bXBNTTpPcmlnaW5hbERvY3VtZW50SUQ9InhtcC5kaWQ6M2E2OWY2MmE" +
            "tZDg1Yy1kZjQxLThhN2UtMDllMGYwZGRjNjI5Ij4gPHhtcE1NOkhpc3Rvcnk+IDxyZGY6U2VxPiA8cmR" +
            "mOmxpIHN0RXZ0OmFjdGlvbj0iY3JlYXRlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDozYTY5ZjY" +
            "yYS1kODVjLWRmNDEtOGE3ZS0wOWUwZjBkZGM2MjkiIHN0RXZ0OndoZW49IjIwMTktMDMtMjRUMjE6MDI" +
            "6MzItMDc6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5" +
            "kb3dzKSIvPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0iY29udmVydGVkIiBzdEV2dDpwYXJhbWV0ZXJzPSJ" +
            "mcm9tIGFwcGxpY2F0aW9uL3ZuZC5hZG9iZS5waG90b3Nob3AgdG8gaW1hZ2UvcG5nIi8+IDxyZGY6bGk" +
            "gc3RFdnQ6YWN0aW9uPSJzYXZlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDoxMTE0YjI2Yy1mNTh" +
            "jLTg0NGQtYTRiYS1kYmQzYTdkMjdlMmEiIHN0RXZ0OndoZW49IjIwMTktMDMtMjVUMDA6MjY6NDMtMDc" +
            "6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSI" +
            "gc3RFdnQ6Y2hhbmdlZD0iLyIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9yeT4gPC9yZGY6RGVzY3J" +
            "pcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz6e02dSAAAH/Ul" +
            "EQVR4nO2d+1NUVRzAz7l337AgiwsIiggYYKmjjVja0xmcbBrLR5NapIX0Gqefmukf6B9oBqMRLaPJ1NS" +
            "mx2DZlKM9VFIry+UZIgghiIKwsMvuvacfnGkUXO7u3nPP3u/2/fy4e/b7/c5+9u59fe85lBEEElKiC0B" +
            "iA4UBA4UBA4UBA4UBA4UBA4UBA4UBA4UBA4UBA4UBA4UBA4UBA4UBA4UBA4UBA4UBA4UBA4UBw8I3XFi" +
            "yvr/gzZaMBRY1xDdy0sAITQ2NvNP4Vnwf5yysLb3E51kYkqxEdvCNnEwwGv8fG+e/xMasB0OSlW/M5EN" +
            "iSvyf5VjHgDPrj5lLOQZEpsJT2FnvAyPWNI4BkalwExaU7aezV/KKhkSCm7ALmUv7XLm8oiGR4CNMpfK" +
            "ZrBWqjoMfJEr4fMWX3fPaZpRyCYVMD5/zsHPe8jGLSyOTGl7T9WVKeJQRyiWpaZGYOm5xncxddd2eyT0" +
            "4B2E3bemNWQ9qDpOZUnGlwRke15/R/KhUvpC5xAhhHP4Sz3nLb9g9msMYoeOyxlaYNIxZXAbt0fUGDUn" +
            "WU9kPcSkFiQa9wpoy7utyz+NSChINuoSpVD7nXa5QmVc1iCa6hF115vzpWcyrFCQadAk75y0fseHFQ6H" +
            "oEtaYrX00j/BFl7AhWwavOpAo0SVM1nEjDokPvFwLDBQGDBQGDBQGDBQGDBQGDM6NpIJRqKxSadL9UEY" +
            "IJcyihmONFpYsjNCp0SSmmucEBrAwRmh9yfZOdxEl6u2vK1SeNdZb7auxxtIurlL5w9JXu1LnyewO04x" +
            "Ief7ul5tr4/gFGAFgYYSSq86c3pS8qe8wQtnkTUUDRkifM7fPNWvqWzJTiGnaGiDvwxixsrv/6mWm0Bh" +
            "n7qSRL9zILEyIWSYChSzsfwkKAwYKAwYKAwYKAwYKAwYKAwYKAwYKAwYKAwYKAwYKAwYKAwYKAwYKAwY" +
            "KAwYKAwYKAwYKAwYKAwYKAwYKAwZsYZFmQYq1KVHPpwQDu5FUpZLE1KnvSExlMX75t1qy7xpNpZJ5Gkk" +
            "hC2NkQ8f+Eaubsju6PFUqOcNjsXZWS0zd+Pe+Uat7kjNGqSvslyN0rIoHsDBKWNFwK8do84dbeEUzDtj" +
            "7sP8hKAwYKAwYKMwQbGrQoMgozBD+8izud2YbERnwUaJpOetdXl9SPW5xGhEchXHml5xH9s3fGpx2rSA" +
            "9M0yiMJ78OOvxA8WVQdk+/TA9M1WjMG58P/uJg0XPa87NnD4xVNm6J+4sKIwDjNCjc9d+UbBR05YnOLj" +
            "dt1PPJRUUxoGvCtZ/PXed5sX+rPG+at/OgpEOPblQmC5UKh0pfO7bOU9pjsz191Q1vZc/2qkzIwqLn5B" +
            "k/azo+eN5FZoj54x2VftqZo316E+KwuIkJNn2F1eezF2lObJgpOMVX413/CqXvCgsHoKyo76kqjFrheb" +
            "I4uGW7U21mYEBXqlRWMz4ran191Sd95ZrjiwZaqpqei8jeJ1jdhQWGyPWtL2lr1zIXKI5ctHgb9uad7l" +
            "DN/kWIFaYWRoj4mTYNmN32RvNGfdqjlw60Phi656U0Cj3GsQJo0R1QF48bNDh3V32ent6iebIZf2nKls" +
            "/cIbHjChDnLCwZD2a/7RTGdOzQt+Sa2dz/VeiGTnomHnWu3xCtt+1ESomKGGM0N9n3t/pLtQc/PA/xze" +
            "31VvVCZ1JIyFOmELlb/K1TzCnJzNwLRphA86surIdl9KKdKaLlVU9x579e58llok1YwXSQYfEVEsU7Wa" +
            "9KXl1ZTuupOYLKOl2Vnc3rO/Yb/Rks5CERUNXasGestd7U2aLTEoZe+ry52s7DwvIlVTCOt2FdQt2GHR" +
            "vPhISU565dGhN15di0iWPsLb0kroFO6JZPpUjlLGNHfsruhuEZUwSYb6MhR+WvjpkF7o8lk2Z2NRe//A" +
            "/x0UmTQZhFz2LPih97aYtXWRSuxLY0vbRir6TIpOSJBB23lu+t6R6XGuddr7YlcDWlrpl/adFJr0FbGF" +
            "nsld8Mv8lwbZSQyPbWnYtvnZeZNL/ACzs55xHP52/VbNFiS9pE8PbWnYtHPxdZNLbgSrsh7zVB4tfELy" +
            "EdNrEcHXTztIbF0UmnQQwYZSphJBjc548UrhJsC3veH9Vcy3HJ9LiQ5cwKnaBC4mpVjX0Q97qQ4VbBD+" +
            "PnDPWW9VUq7PhiQu6hAVkQ9rHI8OO5q/tSi0QbCvPf6XaV5Pn7xaZNBK6hBUPtwRlB5/tjDFGpZ6U2dN" +
            "0pYcla3v6PbEG9gQHPYFrTKvF864oVJ4RvLHu0oFcP4eGJy7EugjQHQRlh8rvx65Q+d1Fb0dzzyl6iod" +
            "bK1t3ewKDcU4EQahNnTDJymG30LWF2ZUArzoIIYzQSfMB6KR0yPdyUy3fHpiEY6KjREWSOe6c7r1+oaq" +
            "51j3BuQcm4ZhIGEeWDvy6taXOFfYnuhD+JKGwZf2nX2jd4zKmBybhJJuwlX0ntrTttSlG9cAknKQS9lj" +
            "Pd5vbP5ZMs4SvESSPsIruhvWXDiS3LZI0wm71wPA9KzAn4IXJTFnbefjJy18kuhBBwBYmMXWD2B6YhAN" +
            "YmEUNb2qvf7T3+0QXIhRzCVOjnkrJoQQ2tdWv7DthaD0mxFzCUsKjrrB/+scXVCo5lMC6joMPXP1JWGH" +
            "mQdfVekQ8OJsbMFAYMFAYMFAYMFAYMFAYMFAYMFAYMFAYMFAYMFAYMFAYMFAYMFAYMFAYMFAYMFAYMFA" +
            "YMP4FchpXcjuHgSkAAAAASUVORK5CYII=")]
        public string TwitchPage1 {
            get {
                return ((string)(this["TwitchPage1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAIAAABoJHXvAAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAGOWlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTAzLTI0VDIxOjAyOjMyLTA3OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjA" +
            "xOS0wMy0yNVQwMDoyNzoxNS0wNzowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOS0wMy0yNVQwMDoyNzo" +
            "xNS0wNzowMCIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHhtcE1" +
            "NOkluc3RhbmNlSUQ9InhtcC5paWQ6YTk1ZjQzZTMtZGQzNy02ODQwLWEzOGEtNGEzMGFlNjYwMTc4IiB" +
            "4bXBNTTpEb2N1bWVudElEPSJhZG9iZTpkb2NpZDpwaG90b3Nob3A6NzI4YmVjYWEtNGFjNy00NzRlLWJ" +
            "kOTktNzYxMmM4ZWJlOWI2IiB4bXBNTTpPcmlnaW5hbERvY3VtZW50SUQ9InhtcC5kaWQ6MDhkNGMxZGU" +
            "tODQ5ZS02MzQxLThiZWItNGQyYTFjZWZhNDNiIj4gPHhtcE1NOkhpc3Rvcnk+IDxyZGY6U2VxPiA8cmR" +
            "mOmxpIHN0RXZ0OmFjdGlvbj0iY3JlYXRlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDowOGQ0YzF" +
            "kZS04NDllLTYzNDEtOGJlYi00ZDJhMWNlZmE0M2IiIHN0RXZ0OndoZW49IjIwMTktMDMtMjRUMjE6MDI" +
            "6MzItMDc6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5" +
            "kb3dzKSIvPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0iY29udmVydGVkIiBzdEV2dDpwYXJhbWV0ZXJzPSJ" +
            "mcm9tIGFwcGxpY2F0aW9uL3ZuZC5hZG9iZS5waG90b3Nob3AgdG8gaW1hZ2UvcG5nIi8+IDxyZGY6bGk" +
            "gc3RFdnQ6YWN0aW9uPSJzYXZlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDphOTVmNDNlMy1kZDM" +
            "3LTY4NDAtYTM4YS00YTMwYWU2NjAxNzgiIHN0RXZ0OndoZW49IjIwMTktMDMtMjVUMDA6Mjc6MTUtMDc" +
            "6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSI" +
            "gc3RFdnQ6Y2hhbmdlZD0iLyIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9yeT4gPC9yZGY6RGVzY3J" +
            "pcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz7lBBGnAAAHT0l" +
            "EQVR4nO2d629URRTA58zce/ugpbSwLVCe5dEWBQImRdBoNJEYYzAaE41IiEFEDPGTif8I0ATEKCYEjMT" +
            "IBz5oDMGYSNCoMbGlBcqjvKFApVu29zHHDxgDtOXu7p073bOc38d27jkn+9v7PjsD6wVDCTnRBTCFwcK" +
            "IwcKIwcKIwcKIwcKIwcKIwcKIwcKIwcKIwcKIwcKIwcKIwcKIwcKIwcKIwcKIwcKIwcKI4RiOJ11vyce" +
            "qfgnqwHDk8gFEcCd3/JPiNjYsTNa1qoalQrqgKs1GLicQij+wGT4kOo2rhXTNxixDMCp6U5PCoKpRTlt" +
            "pMCAzGpPCVOZpcCcbDMiMxpwwVaGanjEWjRkHY8LU1JWyeqapaMx4GBIGSjWuEQkufpg8MfMRy9r5ckq" +
            "bkVDMozFzH6YyHeBUxwzSYXj+EIZDQoCRpKULauFUOzNfhIqpxmMbEAZenWpcHT8Oo+DCYRHeTZ6RAKD" +
            "U1BVpCDNwSFSZDqhoyGMggIrbC8sFcKpTOqMnDipd1fSsiUqYvEgqTNU/KWvnGymFyYdkwkCpzCoBylA" +
            "xTDyJhEHVdNmw3FQpTD4kEqYyHeDxw0OrJBLmNOVxNc8YJdk5zKs3VAaTL8mEJXgRxxQHP64lBgsjBgs" +
            "jBgsjBgsjBgsjhunOX8uAGuctBgodFhxNOmO/XEVdOjcwpIWB1/q+rF2AQj/wV1B6+JLftV0U1C4Oymv" +
            "bImvmIz5gGoTU2X7/RGcx34AUoCwMBFRNh0nNo3cKKUBAwY0IUDUTqmeM3gwwKp22BsrnMBQCx/7WI0Y" +
            "Ciwg4znEPQ1FMuFSgLOyxhIURg4URg4URg4URg4URg4URg4URg4URg4URg4URg4URg4URg4URg4URg4U" +
            "Rg4URg4URg4URg4URg4URg4URg7qwsdsFofCmxHubJarFCrQbSQVIgXr0fxB1MZ2fqMeMJkCWTiMpZWE" +
            "ogr794NYKfLDLEySGwwV3VqMOTu8Dt/ZhZwAYZsfrWLUPZWEC9WCv0Wg95qKlBfVz2GMHCyMGCyMGC0s" +
            "F1CMpRWZhqaAalkNVUxqRSV8lligqs8pr3SycqjSCszDDqOnPeYs2ikevFZRghkkWZhJnxgvuwg1CVcS" +
            "MSzBTNQszhjPrZXfB+ti5mdG/HfTuKT5L0Vsy9wHO3HXuvDfjbY0M+F07kjxSYWEGcOe94cx9PfZhP96" +
            "94nft0Hf6kuRiYckA6ba85cx+NXYgZi/63Tv10NmECVlYAqTrLljvNL8UO1APnfe7tuPwxeQ5WVixSM9" +
            "duMGZ+WLsQH2nz+/ajnevGknLwopCVXqtm1TjmtiBerDH7+7E3HVTmVlYwYBb4y7epDIdsSP17W6/eye" +
            "O3DSYnYUVBriT3bYP1NQVsSOjgT+CE7sw+MdsAXaFlUpjRJGAN8Vr/0jWPxE7Mrp+POjdg8GQ8RpsCtO" +
            "kFw+DyozXvlXWtcaOjK79EvR+juFwGmVYFCZdZ85rGA0n2dH0jd909kI+I6FymsqsEqpi7EaowkAhQE1" +
            "7Sta2xA4NLx8JTu4V2k+cdGwsCgPlzIm/wXw0fu6GyEMYVDV67dvk5AUJ0xVKePH74PS+wibWLBBSFx2" +
            "o82k3g0nNXvs2WTPHQkX3E/YfDvr2pz3ZLClheSBr5rntW+WkWVazIobnvg3OHrSQqqyEydoWb8m2lN7" +
            "NjwtGwZlvwvOH7GQrH2GyrtVbsi2/5VPNgRj07Q/7D1tLWCbCZP1Sr20LVNhdHivyg1N7w8tHbOYsB2G" +
            "qYZnb9iF4dVazRjn/5JfRlZ+sJi0DYSrT4bZujl+n3SxRzu/ZHV07ZjWpEIK6MNW0xl30nmVbGNwJenZ" +
            "FN363mfR/CAtT05/3Fm2Mb1EyCvqDQc+uaOBPm0nvh6owp3mtu/Bdy0tIoz/od+/Qt/62mfQhqAlDLYR" +
            "wZr/itrxt29bda/6JTqO/SCuGhMLsLnCBWujAaV7rtrxj+ffIOHzJ7+5M2PBkhETCQKXSPj4+6MxZJ2v" +
            "mWbalsxeCru06228z6XgkEqYHe4SqNLOfIQqQctKsR3WlS1fWLS448MgA5m7EtniODSgcuRWcOYBZAw1" +
            "PRoD1SbZWlQa/7ADKW/ZpPu+c8kcP9vq9n2FuoLg6QQBqv0RWDrtHsnNYlDNUhhBCoICH5wNIhr7d5Xd" +
            "3JumBKZU1qO6jlK4SpTK4v0Y3/wpOdKJvuAdmwiklYeaIrv8a9OzGMDvRhZinDIVF144FvXtS6oGZcMp" +
            "NWHTlqH/yCxGl1QMz4ZSVsPDiD8Gpr0pnCd80KB9hYf/h4MyB8rYlykbYfz0wRu8KShP6wjAKzh4Mz30" +
            "30XVYgrgw1JZ7YCYcysJ0GJzaG176caLrsEqpCcv7EW2U80/uja4cTbOYUqTEhIVDGGZjfr4AUkS5oO/" +
            "r6OrPtsoqIZI9rWesw7O5EYOFEYOFEYOFEYOFEYOFEYOFEYOFEYOFEYOFEYOFEYOFEYOFEYOFEYOFEYO" +
            "FEYOFEYOFEeNfGzwN0sOxzKAAAAAASUVORK5CYII=")]
        public string TwitchPage2 {
            get {
                return ((string)(this["TwitchPage2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAIAAABoJHXvAAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAGOWlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTAzLTI0VDIxOjAyOjMyLTA3OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjA" +
            "xOS0wMy0yNVQwMDoyNjoyMi0wNzowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOS0wMy0yNVQwMDoyNjo" +
            "yMi0wNzowMCIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHhtcE1" +
            "NOkluc3RhbmNlSUQ9InhtcC5paWQ6ZGViMjNmZmMtOGQ4YS04NTQwLWE3YzMtOWRmYzYwNzhiMTA3IiB" +
            "4bXBNTTpEb2N1bWVudElEPSJhZG9iZTpkb2NpZDpwaG90b3Nob3A6MWIxNDA1MmYtZjg5MS04ZDQ5LWI" +
            "zNjctMjE3ZDlhOWQ4ZmI2IiB4bXBNTTpPcmlnaW5hbERvY3VtZW50SUQ9InhtcC5kaWQ6ZmFjZGIyZWI" +
            "tNDgxYi01YTQ3LWI5NjUtZmNhODJiODBlZDZlIj4gPHhtcE1NOkhpc3Rvcnk+IDxyZGY6U2VxPiA8cmR" +
            "mOmxpIHN0RXZ0OmFjdGlvbj0iY3JlYXRlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDpmYWNkYjJ" +
            "lYi00ODFiLTVhNDctYjk2NS1mY2E4MmI4MGVkNmUiIHN0RXZ0OndoZW49IjIwMTktMDMtMjRUMjE6MDI" +
            "6MzItMDc6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5" +
            "kb3dzKSIvPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0iY29udmVydGVkIiBzdEV2dDpwYXJhbWV0ZXJzPSJ" +
            "mcm9tIGFwcGxpY2F0aW9uL3ZuZC5hZG9iZS5waG90b3Nob3AgdG8gaW1hZ2UvcG5nIi8+IDxyZGY6bGk" +
            "gc3RFdnQ6YWN0aW9uPSJzYXZlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDpkZWIyM2ZmYy04ZDh" +
            "hLTg1NDAtYTdjMy05ZGZjNjA3OGIxMDciIHN0RXZ0OndoZW49IjIwMTktMDMtMjVUMDA6MjY6MjItMDc" +
            "6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSI" +
            "gc3RFdnQ6Y2hhbmdlZD0iLyIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9yeT4gPC9yZGY6RGVzY3J" +
            "pcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz5/TQEnAAAHzEl" +
            "EQVR4nO2d/W8TdRjA73vXdu22ruylXffKVrZ17wuQDEGj0URijMFoTDQiIQYRMYs/mfiPAEtAjM6EgJE" +
            "Q+WE/aAzBkEjQqGxs7bqxjb3A2HtZu3Xt3X39gWgGtLv27nvXe8rz+bH93vM86af3/tx9SQ2HQILPdgF" +
            "IZqAwYKAwYKAwYKAwYKAwYKAwYKAwYKAwYKAwYKAwYKAwYKAwYKAwYKAwYKAwYKAwYKAwYKAwYFjYhuN" +
            "5a1frFyXFrbKcYBs5ZyAciSfWbtz6Ut3ijIUVu/xlJR08b+UEO9vIuQQh6jdsjDeJXs9+nreyjZl7yFR" +
            "SvSxLYQ6Hx1O2h2FA5FlYCvO6X7BZixgGRJ6FmTBByKssf5FVNCQVzIR5SvcU5Feyioakgo0wQgSv54C" +
            "Wgx8kTdj8xEXO+pIdzUxCIdvD5jzM6+62WPK3HyPL4sTU1YQY4TjCJKlpoVS2WPJrKl+z55UyD85AmM3" +
            "m8nr2Kw6jVJqc6RfFDe0ZzQ8hgrt0tx7CGGwSve5ue15JGgOJRVBYC3MGqyWf12ePrjUoz1sry19iUgq" +
            "SDlqFlRa3FznrmZSCpIMmYYQIXvc+QgRW1SCKaBKW7/CWlXSxKgVJB03CvO5umw0vHhqKJmEV5cpH8wh" +
            "bNAnLsxWzqgNJE03CtNyIQ9SBl2uBgcKAgcKAgcKAgcKAgcKAwbiR1GAIEVL0JVBZFjONxvOWpDdXKZW" +
            "paU5gQAsjbf5PXM5dlJO3fsoTIbp+//bwqYzaxQkR2ptPFBXWy/QJ04TjI9HpwWCvin+AHgAWRghX4PA" +
            "WFlQl/5Jk3IhQ4KgsyK949nNKJfO0NQDeh1HKPbU2bPlK4qiKgMm3ezIVORXh9AGwsOcTFAYMFAYMFAY" +
            "MFAYMFAYMFAYMFAYMFAYMFAYMFAYMFAYMFAYMFAYMFAYMFAYMFAYMFAYMFAYMFAYMFAYMFAYM6MKStwu" +
            "qaErcZimztCRyHAe9kZQQnlL52a9kKqv4mWUqJ43GEd481gALo5QLjV+0WZ2UPtHlSQgviuuZdlZTKof" +
            "uXrBZnfKTzgghCTFKU3SsGg9gYRxHV8MhhtFWwiPsoukF9H3YcwcKAwYK0wudnp5AYbogyZs6RUZhulB" +
            "W0pXvKNcjMuijRJPide9r8x+3WBx6BEdhjKnyvtzSeFTYdq4gXsMbJlEYS6orXm1uOCIIedsP0/KmahT" +
            "GjJ3Vb/h3HVacbWEzvjoUOq86CwpjAvHtPNRQ956irdjm0sDwaS2XVFAYAxrq3vXtfEfxFsH6xtzA8On" +
            "w2riWXChME4Twjb7362veUhwZic4OBs48ikxqzIjC1MPzVv+uw7VVryuOXItM3R4+FV2f1Z4UhalE4G3" +
            "NDUeqK19THBleGx8YPrW+8ZBJXhSmBkGwt/mPVXgOKI5cCY8MBno3YgusUqOwjLFaC9uajpW7uxVHLq8" +
            "GBgNnYpvLDLOjsMywWYvamz91l+5WHLmw9Ped4Nl44hHbAowVZpbGCJXk2XZ0tnxeUtymOPLhwq2h0Pl" +
            "EIsK8BiOFyaAnD3PY3R0tJ4tdfsWRD+Z/Hw59I4rrepRhnDCet/pq3xaldaJ2RaMcN7/4ZyQ6k85gh72" +
            "s3L1PEPK4pI1QmeWlhCOesr1FTp/i4JkH14KjfZIc15g0FcYJI0Sor1U+wdyeWGwxHWEOh6erpcdVtEt" +
            "jukyZmv155O6FjF6smSmQDjoolVO9IHErhQVVnS09zsJaA0rayuR0f2j8ot4vm4UkLB2KCus6Wk4WFlQ" +
            "bmZRSOn7vytjkZQNy5ZQwl9PX2dqj0735VFAqjU78ODF11Zh0uSOs2OXvbO1Jb/pUZlBKQ+MXJ6f7Dcu" +
            "YI8JKizvam0/Y8wydHkuS4sGxvpkH14xMmgvCyko6O5o/s9lcRiaVpFhg9LvZud+MTMrlgLByd3e7/7j" +
            "iPO1skaTYnZFzc/M3jUz6GNjCKsoPtDZ+bLCteGJtaOTs/OJfRib9H8DCqryvtDQeVWxRYks8Hr4zcnZ" +
            "h6R8jk24FqrDaqoPNDR8ZPIV0PB6+HTi9vDJkZNKnACbs8ROSdTVvNvk+MNjWxsb8QLCX6RNpatAozNA" +
            "JLiiVZTlRW3WwyfehuqeYVRNdvz8Q6H2kreGJCZqEWQRd2sdTQ321h5yFdQbbikRnBoZPrUWnjUyaCk3" +
            "CVsIjgmBns55RyhHeWVC9TVc6z1t3uJoyDRzbXNqILSq2eCaFEGFzc2V04lIkyqDhiQmkRsPCgmBn+Gc" +
            "nRNjb+ZUrjXtO6bMaDg2Fvo7FljiVdRJZjptk5rDHaFrDJCnGqg6O4ziOcJTlTnF5dXgw0Mu2BybrmOg" +
            "okecFtetBEhaXBwaDvfE44x6YrGMiYQx5uPDH0Mi5hBjNdiHsyUFhc/M3h0LndeqByTq5Jmx27npg9Ft" +
            "J0qsHJuvklLCp2V+CY9+bZwpfPcgdYZPT/aMTl3LbFpczwu7eu3J38jJlelZgTsALo1Qam7w8fu+nbBd" +
            "iELCFUSob3AOTdQALk2UxONY3ff/XbBdiKOYSRtJ+lZIoxYKjfbNz13Wtx4SYS1hCjCTEaPL3uP4HIbw" +
            "kxUbHf7j/8IZhhZkHTVfrEePBt7kBA4UBA4UBA4UBA4UBA4UBA4UBA4UBA4UBA4UBA4UBA4UBA4UBA4U" +
            "BA4UBA4UBA4UBA4UB419t40QSuGpAggAAAABJRU5ErkJggg==")]
        public string TwitchPage3 {
            get {
                return ((string)(this["TwitchPage3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAIAAABoJHXvAAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAF0WlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOnhtcE1NPSJodHRwOi8" +
            "vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIiB4bWxuczpzdEV2dD0iaHR0cDovL25zLmFkb2JlLmNvbS9" +
            "4YXAvMS4wL3NUeXBlL1Jlc291cmNlRXZlbnQjIiB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2V" +
            "sZW1lbnRzLzEuMS8iIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3A" +
            "vMS4wLyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTAzLTI2VDAwOjM2OjA4LTA3OjAwIiB4bXA6TWV0YWRhdGFEYXRlPSI" +
            "yMDE5LTAzLTI2VDAwOjM2OjA4LTA3OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjAxOS0wMy0yNlQwMDozNjo" +
            "wOC0wNzowMCIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDoxZmIwZWZkZS1mMjhhLTBhNGMtOTZkNi0" +
            "wYTk2NjdjMTQxOGMiIHhtcE1NOkRvY3VtZW50SUQ9ImFkb2JlOmRvY2lkOnBob3Rvc2hvcDoxMzRjNjE" +
            "0My04YmEwLWU1NDUtYmQyYi1kMzFlNDY0NjE4MmMiIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1" +
            "wLmRpZDoyOTVmOTMwOC03ZWY5LWVkNGYtYmNhMy0yMTkxNzgyMzc1NmYiIGRjOmZvcm1hdD0iaW1hZ2U" +
            "vcG5nIiBwaG90b3Nob3A6Q29sb3JNb2RlPSIzIj4gPHhtcE1NOkhpc3Rvcnk+IDxyZGY6U2VxPiA8cmR" +
            "mOmxpIHN0RXZ0OmFjdGlvbj0iY3JlYXRlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDoyOTVmOTM" +
            "wOC03ZWY5LWVkNGYtYmNhMy0yMTkxNzgyMzc1NmYiIHN0RXZ0OndoZW49IjIwMTktMDMtMjZUMDA6MzY" +
            "6MDgtMDc6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5" +
            "kb3dzKSIvPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0ic2F2ZWQiIHN0RXZ0Omluc3RhbmNlSUQ9InhtcC5" +
            "paWQ6MWZiMGVmZGUtZjI4YS0wYTRjLTk2ZDYtMGE5NjY3YzE0MThjIiBzdEV2dDp3aGVuPSIyMDE5LTA" +
            "zLTI2VDAwOjM2OjA4LTA3OjAwIiBzdEV2dDpzb2Z0d2FyZUFnZW50PSJBZG9iZSBQaG90b3Nob3AgQ0M" +
            "gMjAxOSAoV2luZG93cykiIHN0RXZ0OmNoYW5nZWQ9Ii8iLz4gPC9yZGY6U2VxPiA8L3htcE1NOkhpc3R" +
            "vcnk+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5" +
            "kPSJyIj8+Z/pWLgAADDBJREFUeJztnW1sFMcZgHdn9/Z8vrPvzmeD8eGzmwTSHKXKQVMQqpofARKlhAp" +
            "UJKchEVGcUiBNUZVC0tRqI5oSEqmiCeQLV6BCBUlUkChEqNA2pZKTooITIixCUnDt+Dh/nM/2ne9zd6Y" +
            "/LiUOkNm9u5ndHTrPX6+94312Zt6dr1d8ds3HAocdgNUF4JQGF8YYXBhjcGGMwYUxBhfGGFwYY3BhjMG" +
            "FMQYXxhhcGGNwYYzBhTEGF8YYXBhjcGGMwYUxBhfGGFwYY3BhjMGFMQYXxhhcGGNwYYzBhTGGbHUBKiI" +
            "YkhYs9QRmON1eRa6SgCyKQBAEQRQBQhBBAUEBQaRmtVxGTcTyZ7tSPd15q0tdESJzS7WXrHB/daHX5VU" +
            "khyQCsdRfRxBpBS2fUi+enTh5NDUWhzQKSQ9mhK1s9950u8/hksuQ9GUU5UXPTxzZO8aKObsLC0eUpQ9" +
            "Mc/mdBD1dC4KokFE/+MvI8UOT9O5CBPsKW7LCHbm7QXaa2stqBXWgZ2Lf9lEzb1oSdhRmiaqpQBX2vj9" +
            "2YKcdtdlLWDii3PvIDMXtsLoggiAIWkH9x5uDXScyVhfkC9hI2KMd0+pba6j2VSUDUTqR27M1ap+QRLr" +
            "r9setLoMQjigP/7K5psElinayJQiCKDqq5fmLfS4pf/F8werSCIIdPpzbNtR9ZZ7fXhXriwAg3rGs8ZZ" +
            "5k690xKwui9VN4o+2NdVMq67kLyCIoKZpeZSbLKh5mE1pmZSWTqrVNbIgCDV1cpVHdrodkiICqZwP7ak" +
            "UMuqujj5rm0fLhPkCoP2Z5jLjC4jUgpYczn7w9/GSgoJwRFmw1Fvf4padZcrTCuq+X/UP9Gll/C4RrBH" +
            "mC4AfPBsqI3DXCupof/qtl0cqf81Xtntvnud3OCWhRHMQosM7+q0ak7RAWDAkre4ISbJUwu9AlM+ob//" +
            "uMvHHFAxJqx6fUepICoTo5P6oJRG/2cJ8AbD2uZYSbEGUTeWP7Rmk+kb7AuDBTY2eepdxbVbVM1PD+s9" +
            "aQsVoS6gV1JNvxN58OT4co9tnZDPo1InkaP/kzV93Sw5Dc4SiKM6+o3a0f5J22a7CVGGPvRByuIxFGRA" +
            "NX0q++NOB/osq5UJ9znBM6zo61tCg1c2sNvJFKIrirPmec10T2QwyoXhFzJtxXrel0WBMCFX4zv7ori1" +
            "DtIt0XQ52ju99plfNGXpRJFl6dEuIdpGmYpKw5Q/V+pvcRq4sZNRXn+y1dgRvoE97/oe9yaG0kYsdLnn" +
            "dlkbaRbqCGcKCIWnOnQ1Goud0PPvC+l6bDNy9tDl6+fy4APWbO3+Te8kKQ69j5Zgh7PtPNhuJvhKfprY" +
            "/8akJ5THO7m3DF88k9J0Bcf69030BMx4m9Xus3ljncOmHhcmhtB1G6q7lwM5RI86ADNY81WRCeegK8wV" +
            "A81y/7mXZidxLm6NUS1IJB3aODvcmdS+r9jsXLXbRLgxdYWueatJtDNWc+psf91MtRuXs2jKkH4MA8Vv" +
            "fm067JBSFhSNKtd+JvwZC9PrTffTKQJCXNkd1Y33ZKa9s91ItBkVh9z4yQycyhOj0kZhNYkIj/OHX/Ui" +
            "vM5u1oI5qGWgJC0cURS/WSI5k7L+sbCoDfdqlMwn8NZIsUa1ktITds2Y6vnpBiPY+b8ewEM+BnaOFjE7" +
            "DOOub+nFW2VAR5gsAp0fBX3PhXQJzWpZwdFcUH+VLDpleuEhF2Kr19fjgUCuoBzvHadzaBHq68+lEDn/" +
            "NwvvqKd2dirC6Zp1lGh+f0ukJbM5bL17GRx9Oj0Jp4IP8Hw1HFMmBCzc0VWO3ehUZ6NNyKdzUpQjEe9p" +
            "8NG5NXtidK3Xi2qFPUsRvaj7v/WkEf8HM22po3Je8sJqGKsxPEUSHOuPEb2o+XScymoqbazYygloGhIX" +
            "5AkB24NZrFDIqo8HhtUzEcJN2IhBpzLkQFvbt73jwn18X3x8je0cLObxrGH/BLfPIt4qEhbXM8eB+DNF" +
            "fD+kPe7PCQJ8GVVxr4QngeofyICysqgb3vaxp2g3THhbJp3E7JCRnKWsvjUFYGH6NWDrB9g7+a4lewI2" +
            "FAkEg/jVG+s9hO7DhvizZ21nO2S7sJwoQwxGdCaZSISksHFHwEYfOv8cgPd15/JBH6FbCg4okhQVbscs" +
            "OIWL9UJPrghfmb9QZBC8VksICTbjqf0MFG1OAGu4/kxUb92EuD/mgyP4g7JvoqCL8TEgKkxVcB4bgjVn" +
            "H8E0ikGxcw/DVH2nm7RgwE3yTSBx+/B5jkBSm5nHvmvh/+W4Qr39kheEaPfEGNSZhZyeIQ/Ihjsd1JmE" +
            "J3ss+4N/DQpbw/kySwmK9OsLM2d9hMgBbw7IpwjtIST7Bnm6dtUTEB9bsAP4JDv6H8PApSWFjcYj/KLl" +
            "1Pna2jEEWLXbhh09Pv0N4aTPhNgpquCbb30R+Qs9a8K8ggoj4mTmEhWnYQFGptsVBiAQJYFdg4l/f8iA" +
            "sbHwQty4FyCAYuqHGG2Xs0qhCxvbCzr2rs2Rj6f10d+OYyaLFLvyEbSJKfsKWsLCuExl83DHtZpN225u" +
            "A7gL6f/6Z/AJn8h9G+N04kkMORwjP6VkFfocOVCGNCVvywmKf6LSKd7XR2tlhJm0b6vBjN9lxKtPr5IU" +
            "d2TuGbxU99a4bYMgjNLcWf8GpY1RWpJN/cGNxqOZw0ZEIxPs3TiN+XzNZssKNP50TqpDS6UtU3vSP3tM" +
            "5ot/X5Ga6kkXubsBfMB4zdE5VGVB5aod/P4FfwywC8cFN5h2oRZa2DXU6h99CpLvsvmxoveaDeqFHTb2" +
            "LxXDRFwCt83T2nGdTeXqnONMStnvbMMQfaQHEZWvNOJyJLGueasJ/LAsQHdszSK8AFDuSuN75TLLT1JM" +
            "GK2f5Q7W6Z/tkU3mq62UpCnvr5RGdSmbuSYMVEgxJYd1THylXL4GqsLE4/PRDvdMCgDh/WaP9OzNfAKz" +
            "+ebNOYygI6USO9nJ0urH1vu2jugdqASAuXz/T5lF++zPN+KMRBEGAEO3ZSv0QQeqP6chrOufGCIIAZLB" +
            "2a8i2zn7yW0MpR3rPJEzYrkj9GfV05xNR/WlyySGv3Rqy4WzZEztaqmr1l6IUMqo5Gf3MeKlf6YgZOVV" +
            "ccsgPdrTYpz/zBcCmV1uN1C0I0a4Ok059NKkVOvJaVDdiFAQByGD5Y812iBvDEWXtcy2G0vmYe+qjSZk" +
            "hhmOaS8oHZ3kEvYwLoigGZ3m+dofzX3+zbLtm24a6hd+dbnDjyeWPJv7YOUa5RJ9jXj9//NBkn26UXwS" +
            "I/pmeTa+2mt88BkPSEztabvqGzlzXFZJD6d3baA0bXhezsxut29Lon2l4daK5OUNLzZpayKgvrO+lWaL" +
            "rYEH+sFLTKEKI4r1JIknevoy2DXUtt3tLSmmm5tTXn7YgvaI1GfrKSH0JIZocyRzcOUhwINwXAKvW1wd" +
            "CHiCX1jVYZUuwMAdmaW3jFSBSC9rwpclDnfGyn5cvAO5p8828rcbhksvYU5OfLHT+ot+qI32szDK7emN" +
            "daK6/1BSUnwGRpmm5CTV2KX22K6U7ghcMSQuWeoKz3C6vIjnKTzebHEpbm8TC4rTAS1a45y9r1B1U1QV" +
            "BhCBCCCL4hW39IhCABEQgVr47DUHU/2Fi33YzhjMwWJx4+/ihyZ7TvQ/8rLmMjLNT+Z8SWl8pUIUn37h" +
            "sbVazItaPtxazqw1fnNBNumANEKXjWctz0F3B4iZxKuGIsmxtU4VVjSxQhaffHrRV+gobCSuyst07e0G" +
            "g1DibOAiikd6kVXk4MdhOWJGHNzdMn11beTBSBgii1Ehm7/M2zeJjU2FFVm+sC84pbQCiEiBE49HJ/du" +
            "H7KmqiI06jGvZt31UEEYXLXYtvK/e6VEoHRyBIFJz2r/PJJhIf2DrGnYVK9u9rXNrFY9CpKkserp8YeL" +
            "I3jE7V6mrsHUNu4qDneOCMC4IQjiiLFjq9TdVOVwSkIwOWyCIIIRaDo4PZs69m7RJmF4qLAm7Qk93vqf" +
            "781koXwCEI87GVsUbUKqmnNmYTWmFnJZOacm42nM6S2/5tJkwKewqxuLFvT1M1phSsX6kg1MSXBhjcGG" +
            "MwYUxBhfGGFwYY3BhjMGFMQYXxhhcGGNwYYzBhTEGF8YYXBhjcGGMwYUxBhfGGFwYY3BhjMGFMQYXxhh" +
            "cGGNwYYzBhTEGF8YY/wXESZjrh7tSTQAAAABJRU5ErkJggg==")]
        public string TwitchNotLive {
            get {
                return ((string)(this["TwitchNotLive"]));
            }
        }
    }
}
