//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatPager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAIAAADajyQQAAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAHMmlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTAzLTI0VDIxOjAyOjMyLTA3OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjA" +
            "xOS0wMy0zMVQyMjo1MToyOC0wNzowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOS0wMy0zMVQyMjo1MTo" +
            "yOC0wNzowMCIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHBob3R" +
            "vc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLml" +
            "pZDo0OTRjNmJjNi0yZjQ3LWM5NDctYTg3Ny1lODkyOWE2NjJjZTEiIHhtcE1NOkRvY3VtZW50SUQ9ImF" +
            "kb2JlOmRvY2lkOnBob3Rvc2hvcDphNWU2NjBhOC04YTYzLWY4NDgtODhjOC1iYWU2YjE3MGQwYjYiIHh" +
            "tcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDozYTY5ZjYyYS1kODVjLWRmNDEtOGE3ZS0wOWU" +
            "wZjBkZGM2MjkiPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJ" +
            "jcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjNhNjlmNjJhLWQ4NWMtZGY0MS04YTdlLTA" +
            "5ZTBmMGRkYzYyOSIgc3RFdnQ6d2hlbj0iMjAxOS0wMy0yNFQyMTowMjozMi0wNzowMCIgc3RFdnQ6c29" +
            "mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTkgKFdpbmRvd3MpIi8+IDxyZGY6bGkgc3R" +
            "FdnQ6YWN0aW9uPSJjb252ZXJ0ZWQiIHN0RXZ0OnBhcmFtZXRlcnM9ImZyb20gYXBwbGljYXRpb24vdm5" +
            "kLmFkb2JlLnBob3Rvc2hvcCB0byBpbWFnZS9wbmciLz4gPHJkZjpsaSBzdEV2dDphY3Rpb249InNhdmV" +
            "kIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjExMTRiMjZjLWY1OGMtODQ0ZC1hNGJhLWRiZDNhN2Q" +
            "yN2UyYSIgc3RFdnQ6d2hlbj0iMjAxOS0wMy0yNVQwMDoyNjo0My0wNzowMCIgc3RFdnQ6c29mdHdhcmV" +
            "BZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTkgKFdpbmRvd3MpIiBzdEV2dDpjaGFuZ2VkPSIvIi8" +
            "+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJzYXZlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDo0OTR" +
            "jNmJjNi0yZjQ3LWM5NDctYTg3Ny1lODkyOWE2NjJjZTEiIHN0RXZ0OndoZW49IjIwMTktMDMtMzFUMjI" +
            "6NTE6MjgtMDc6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE5ICh" +
            "XaW5kb3dzKSIgc3RFdnQ6Y2hhbmdlZD0iLyIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9yeT4gPC9" +
            "yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz4" +
            "BGXoiAAAGXElEQVRoge2aaWhcVRTH77n3rbMlmWSaZWzUqgUpdk2oVkndqlD9oBREBRWtC4o7FFpB2lp" +
            "sU622LoiighsofhBXXAq1lkaraGNtbVptImmzr52ZzLw3b7nHD1PGEpI3byYzOBPmT77k5rx7/z9e3rn" +
            "nvvMAyewU/b8NFEplsFJTGazUVAYrNc1aMMF9qEElIISQotjSkYCAFkU+XYBbsN1zV78/f221PgxFAIY" +
            "EhtTaezpev6b32+liXIFxoN803jCihCyaxR0unJBAvyecEH0OMa6Mttc0dfrn1yf6KNp58jYjIQG/GRW" +
            "54RDjCuz7husQgKGFBIAgJ3RcDnKgkCejbsQBPFbCb0Q5uEp4mcH6vHPbQ02VxjgSIIRYIEjcaOnfI9m" +
            "GTdlM/bqWaBv93vA//gtEbrqJzwy2J7wqIlXWJ3pTvyaZ4jXjjx7eAdNnpAKpre7KHYufCiZHATMnsAy" +
            "3VRM8bXUtATOSHgGCHCAhqDO1mb2STHa/7WaIbKtr6fU1eqz4pHEb/of0yIG630WdwBBgX/3Vom047IN" +
            "FKycwE8QxpUax9VTaKC05gQFBiScRSo+KzOIieNaCFTa59Xrnttc0KbZuUtFvRlcM7JsyD/X4Gn+vXqb" +
            "YmkmlgBFZMbjPzU7lrMKCHQ1e0rp0UzA5Ehf850dPLB/8keIUBd7h4OJtyzbX6MMxwT8/cuzSwf2MzLQ" +
            "oLSyYaiVC2mCFcVoVtKA+Ot2RR7G0kDZYlRyTBb1q+rCsVPBnjCJP/TjYBYJuwrJbNy+zFKHKYKWmMli" +
            "pqQxWaiqD5SQbmM6UJFN0phhMdgxTz4RRKS9LF7akAoIiNyVuWFwQpn+7RAlK3BC5IXFDQBshD+VHYcG" +
            "WDv+yq+0BhjYHKtoGQ2vKsOahn3btv5+hxYFJeXoTUVgwnznhMydchMV8ZixjGM3mLFNKyUO14ja4fUV" +
            "bMmBJpnzXuFqxNEAEghyoc4ekNMASgndz07ZfQ8srjAglnANMCD7GnQ6jRdEWclZUqnimaWtH1YJwvAc" +
            "J2iD0ecOrT35++cAPDlcVO9iYXL25eVtn4KJwvAcQTSr2e8KrTn395KGtzhcWNdiQWrupefspX2NDvBc" +
            "IGkwa8DTc0P3pw4dfyHht8YL1ec/Z1Nw6qNY1xHsJIUkmD3rqbu76+P6jr7i5PGswJADIA0Ykc+gM1BW" +
            "4cEvTs+NysC7RTwjRmTLkqb317/fvOv6myxmyBmNoI2UHQ81eMz5lczE1OC96QrUSk/40rM7p8TYqtu5" +
            "kiJujSuitix+KSJW1iQFCiCaoI0rozuNv3/b3u+59Zg2m2FqSyjsXbSCIOBVYksmM21t/fmJe9MTZ4x1" +
            "VC7Yv2RgTA6qtOcxP0U4yReRmSBsihCQE75hSvbbj9TVdH2blM6d/RYKMW0gApuq1W8BEbk6q9w5VL21" +
            "dttmgUsA47dy7QQIeMy6gSQiZEH0RqerBIy/d2P1Jtj5zTB4OjWAOVODW2fX5L3Mue37J04BYow25bI1" +
            "TxJgUiAu+R47suP7klzk4LFRWTAO01a98cdEGgVuVyXHXVDwqVWiC+vih1qv6dudmoCBgHKhiaYSQPeH" +
            "rXl64TrW0gBFxT3VarrKouK59y+UD+3L2kAEMgXJgzp6QACU83R9BArKdrNFHDtResXPher8Z9Zux9Ax" +
            "IAKdvJVPkY3I1EFx/cGPz0IHscf6TExgHOi4Fx+UqM1MrXbb1tHuGtseKvzd/7d7wtQEz4jMnUuOpL18" +
            "iciUHRqY5WWmip1IfX9++aeFoe65EZwQOZzcObH/dSk1Qnb8Zke3kn8FL9jas8tjx1JkCCUSlCsXSFFt" +
            "PU5lUHFXmXH/yi0WjB00qTpkbE6Jnwejh82OdM6QizneMot3Sv8fNLDLXvzr3JtVOpKhS3zoB4hkq5AZ" +
            "TBtXaNV0f3dvx2sxNu1F+kkdMDLCz9jQgmH6IKHKdqUOe2tv/eueOv97Oy3JuVNgimCLXBM+IErr72Bu" +
            "3nPigoGtNUgHBKPK44D2tBO87+urN/3xcuIWmVN7AUo9WOiVQ5DHRH5MqHjqyc3X3Z/laxb3yAxYXvL3" +
            "ecwwmp0vEJJNlW3/sj+eu7fk6L0tkK6d0717d/vN+Cy1XLS1dIiYEz7xo5+KRX/MxfS7KD1gRqjRev+W" +
            "gMlipqQxWaiqDlZpmLdi/7i6lobNHDREAAAAASUVORK5CYII=")]
        public string TwitchPage1 {
            get {
                return ((string)(this["TwitchPage1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAIAAADajyQQAAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAHMmlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTAzLTI0VDIxOjAyOjMyLTA3OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjA" +
            "xOS0wMy0zMVQyMjo1MTo1NC0wNzowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOS0wMy0zMVQyMjo1MTo" +
            "1NC0wNzowMCIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHBob3R" +
            "vc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLml" +
            "pZDpkMzE5MDg4MC04ZjdlLWVlNDYtOWNmYS1lZGUxNWY1MjhlMjEiIHhtcE1NOkRvY3VtZW50SUQ9ImF" +
            "kb2JlOmRvY2lkOnBob3Rvc2hvcDphOTc2Mjk4Yi01NjI2LTQ1NDAtYjU4Yi1mNzlkZTA3OTU1OGQiIHh" +
            "tcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDowOGQ0YzFkZS04NDllLTYzNDEtOGJlYi00ZDJ" +
            "hMWNlZmE0M2IiPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJ" +
            "jcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjA4ZDRjMWRlLTg0OWUtNjM0MS04YmViLTR" +
            "kMmExY2VmYTQzYiIgc3RFdnQ6d2hlbj0iMjAxOS0wMy0yNFQyMTowMjozMi0wNzowMCIgc3RFdnQ6c29" +
            "mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTkgKFdpbmRvd3MpIi8+IDxyZGY6bGkgc3R" +
            "FdnQ6YWN0aW9uPSJjb252ZXJ0ZWQiIHN0RXZ0OnBhcmFtZXRlcnM9ImZyb20gYXBwbGljYXRpb24vdm5" +
            "kLmFkb2JlLnBob3Rvc2hvcCB0byBpbWFnZS9wbmciLz4gPHJkZjpsaSBzdEV2dDphY3Rpb249InNhdmV" +
            "kIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOmE5NWY0M2UzLWRkMzctNjg0MC1hMzhhLTRhMzBhZTY" +
            "2MDE3OCIgc3RFdnQ6d2hlbj0iMjAxOS0wMy0yNVQwMDoyNzoxNS0wNzowMCIgc3RFdnQ6c29mdHdhcmV" +
            "BZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTkgKFdpbmRvd3MpIiBzdEV2dDpjaGFuZ2VkPSIvIi8" +
            "+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJzYXZlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDpkMzE" +
            "5MDg4MC04ZjdlLWVlNDYtOWNmYS1lZGUxNWY1MjhlMjEiIHN0RXZ0OndoZW49IjIwMTktMDMtMzFUMjI" +
            "6NTE6NTQtMDc6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE5ICh" +
            "XaW5kb3dzKSIgc3RFdnQ6Y2hhbmdlZD0iLyIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9yeT4gPC9" +
            "yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz4" +
            "jQu+5AAAF90lEQVRoge2aW4hVVRjH/99a+3bOmYsz4zijo1NQCSHeZ5AgNCJ9sJfeexQKeushyCBUIrU" +
            "wIoowQigKCh+iG0gEQmJXQjHF62hoXmZGJ50znstea+/19eDMONqcffa5zcyR82e/nLM/9lo/1t7f963" +
            "vW/Q8HkyJ2Z5ArdQAqzc1wOpNDbB6kxXflGs3i7JEkXdLACPhAJgzgAQOwKbQ7VhgDNhLNttLt3D++tw" +
            "AI0p06VN79ZUfCq1bLDAiYfU+K7xOFiWscC1FlOyB3RRhUXyiDFjz+0TzUpO9Cg6rN7lKRNBpGBVhEWs" +
            "FrEWbQAQOAAIYEOS2g2bWoxIhyLJKxxy3CBgDMrVEdvZB3Rz3Q2TBqPDaQQ4VhKx8wnEVKkr1yOZH2Og" +
            "45sVXzOrZCGceZ6/c+UnSY53xj+8xbKIdbnXFgNP9lFz1GvwRcHEHVgRMWEnZvR569J4hiMhKkM7MJBg" +
            "ASDe+bdT7yoDsXk9NvRxk7r9Hs+EeScQPNlFgRCQXPo1QRcTBOauCYAyAbPLmI8wXS1/moqJdJ8P4oPq" +
            "jQiO7L1MM8ERQp8IvdEyzklRbMJlaIub3IcxD2NDpYPDQtH5INvWKjrUIcxAO1GgwdChOpIpWDcEYEO3" +
            "L3TXb2b9BVrNJDwRDv4DvT/AYEO2r3LU7OH+drGYzejoYOgxUmpTWOBwFWc4NsboFK8f5kYJRKMhxboj" +
            "9f2Hlo8xKUe2dB5vxK2q6HM+sBD2wXrEBVm9qgNWbGmD1pgZYeSIJ6U1chTf2JCET42bj9eZKVesdPsN" +
            "oGAVjIaq6xDBq/OIQRJWnHzUEIyC8/kf+5xfBIUhwqMDB9GbDv+YPvwAOQJKrVImo8X5M3zb69uTPgvs" +
            "xPWb0WFGzkvYyNS82xdw1FjVjgIMMKG6Jtj68IgNCelbvZgQ5MAMMEojskNQBGANkpby+XbJzHatRwIC" +
            "IrCaYqM3oHGkLFRQD5LR6fTtF2zLOXAYYZFGqJ7j0bTD4U8QLPKfBGBBuh9e/i1oe48xlMEPYItkT/HM" +
            "gf2wnIr/MuQvGgEh0ef1vUVMvZ64ADOmI5CJ98Wv/+DuoYg96JsWASC32+ndTopszVwBAuiLZrS/s90+" +
            "+jxhetAwwAhtWo9ExZdqBY4YhBqyWR92+N8lt5+w1AJCeSHbpc5/5Zz6OGT9KB+MQQsrOfqEz0zcXSQD" +
            "g9AAH2fumKxILRKqXw3zU440WXqfz+EvkzOPsIABYCeF1qjP71LlP49dSSwbjMAfhOiu3EjNPCyZdmND" +
            "//WWTHpichwGstmXu6m1kt3CYix6ApMdGc24YAKyU8DrUqb3qwhclVYjLehXBMAGDpu+1k4TRU/M9A9g" +
            "da9y1OyAcVreKfSDEOgPWAGA3kdOmTrynLn5Vat27XOcRkaqTgAkmPygD2AuecFe/DmbODcdtyTPDaSG" +
            "rSZ3Yoy59X0YaUTOvSAJ3qBZucFduZRPAvxmbysBpJSuhju1WV38sLzmqDRgJBDkDuD2bnBWvcJCDGi2" +
            "Bym0jYftH39CDh8pO+YqBkQDJYnMiwEzZUxBC3+RvOF1POiteZZ2GHpvyBIpqJbMhtwNg/8g2PfxbJYl" +
            "sJBgJ4bST21a8lR7meXL2HCLIOEu3WD3PsB6Fvj1BdefkyzyQLLSzIjvJ+Zv+0e165GiF6TlFHU8naXV" +
            "vgJWI3NWDQ1+2L7cWbeQwM76nAJHTykEOYf4ulbDJWxBc+i4cOULCnt432kkzcjwcO1957y9yKTjU1w4" +
            "WfYQBHJO3HnoOYXayKck6DeaJNTSQnkh06Qtf+qc+5MjW5gx1NOOMIQCyW+6NaXz3I2IDmRDJLn32E//" +
            "svuh5V7GNX+MkmA2spPA61emP1MDnM3n8oJZgbGClhNeuTn6g/t4/w4cqqghG93wgbGA3k9Pqn3hXXfx" +
            "m5isQ1QEjKyVSi410J1NEki6HefXX2+rygVmpq0S6+9gSzQ/LznUc5CYjL1lJkz4f3Phzto71VAds8gT" +
            "K1H+q5bjLU5Vexf8xzPr5qzqoK5anBli9qQFWb2qA1Zv+A3v8YGq3w8I5AAAAAElFTkSuQmCC")]
        public string TwitchPage2 {
            get {
                return ((string)(this["TwitchPage2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAIAAADajyQQAAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAHMmlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTAzLTI0VDIxOjAyOjMyLTA3OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjA" +
            "xOS0wMy0zMVQyMjo1MTo0MS0wNzowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOS0wMy0zMVQyMjo1MTo" +
            "0MS0wNzowMCIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHBob3R" +
            "vc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLml" +
            "pZDo4OTlkY2YwMy05MzFjLWU2NGMtODUwOC1mYzQyZWQzNjQxMzAiIHhtcE1NOkRvY3VtZW50SUQ9ImF" +
            "kb2JlOmRvY2lkOnBob3Rvc2hvcDoxNTEyZDBiOC1iYjAzLTFmNDAtOGEwMy1iMGMyODQ2YmJjOGQiIHh" +
            "tcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDpmYWNkYjJlYi00ODFiLTVhNDctYjk2NS1mY2E" +
            "4MmI4MGVkNmUiPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJ" +
            "jcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOmZhY2RiMmViLTQ4MWItNWE0Ny1iOTY1LWZ" +
            "jYTgyYjgwZWQ2ZSIgc3RFdnQ6d2hlbj0iMjAxOS0wMy0yNFQyMTowMjozMi0wNzowMCIgc3RFdnQ6c29" +
            "mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTkgKFdpbmRvd3MpIi8+IDxyZGY6bGkgc3R" +
            "FdnQ6YWN0aW9uPSJjb252ZXJ0ZWQiIHN0RXZ0OnBhcmFtZXRlcnM9ImZyb20gYXBwbGljYXRpb24vdm5" +
            "kLmFkb2JlLnBob3Rvc2hvcCB0byBpbWFnZS9wbmciLz4gPHJkZjpsaSBzdEV2dDphY3Rpb249InNhdmV" +
            "kIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOmRlYjIzZmZjLThkOGEtODU0MC1hN2MzLTlkZmM2MDc" +
            "4YjEwNyIgc3RFdnQ6d2hlbj0iMjAxOS0wMy0yNVQwMDoyNjoyMi0wNzowMCIgc3RFdnQ6c29mdHdhcmV" +
            "BZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTkgKFdpbmRvd3MpIiBzdEV2dDpjaGFuZ2VkPSIvIi8" +
            "+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJzYXZlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDo4OTl" +
            "kY2YwMy05MzFjLWU2NGMtODUwOC1mYzQyZWQzNjQxMzAiIHN0RXZ0OndoZW49IjIwMTktMDMtMzFUMjI" +
            "6NTE6NDEtMDc6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE5ICh" +
            "XaW5kb3dzKSIgc3RFdnQ6Y2hhbmdlZD0iLyIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9yeT4gPC9" +
            "yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz6" +
            "tbWIUAAAHAElEQVRoge2a328cVxXHv+feO792179/Jq7dqC1BNCRNGqcJArkVon0oL/wPlVqJNx6QKBJ" +
            "qK0RbUBFCIFSEKoFAAvUB8UuqEFIQUWkSGmIlDnHSuEkdkthOYhLbuzs/7z08OF4C9u6Od722t+xX87R" +
            "zduZ85t45c+45l4bx8ZTYagcapRZYs6kF1mxqgTWbVBojAjSgAWq0O6nFgAQkwGUMUoEZAIAj7JVrbr0" +
            "IZDhhNuUMUoH5wKPDzz66+zk/uLU9wCjjDUxMvjl5/Y/ZMhbVwRLAJbFr5IsZt0+IVA+i8aJcZsi2cmX" +
            "HKw1YCDzcO9rZtjtfvMGsN9C7OkRRvKhNVOGdrwJmAAUM73yGiJgTgBhMEK7TLUhs5qQkojgpRtEiUap" +
            "IXgUsBPqzwwN9o2F0ZzkoClLGRNdmjmodkZAb4HI6aR3lskOdbQ8bE6d5oNVHbHjoacfuzBev3/uDdP2" +
            "4cHrijTwbu25306sAfHrwqf79Xw/CeXB1tEpgEdCpMkODY2G8UPqRwUQklafiwuaNF2ABUjrpJ38lsAT" +
            "YOTjWlhsp+LP/c0qQEpubtgiASKT/2JT1TQMu0fCOz2sdofx3cNuqLBgDNlmu26t1sJ1yqbSqNJsMWJs" +
            "Q1HxU+H/P7muTACKgNI8F4AG06vUvmS1HhnJm61UDwUKgOzvc1zuqdSCEFcWLN2aPaTZitVlupL/nYKJ" +
            "9IewoWrgxd0wz1zmXGgvW0733yOMv++FtW7XdXZyamXvPcLQarLd7/+GDr/jBLVu13Vm4MDP3roHevmA" +
            "CiJNi0Z8Lo7ta+WEwv+b8EkCS+L4/F4T/0ioIgnneiJVRw4MHs7l3VHKX05mtQx/bqNgCaza1wJpNLbB" +
            "mUwusJhFJJV0pXSVdKZ01bRgQJJX07pmJjamkNLoAytrExkTaKGPiskZgbSJjIm0iZg2i+tOPBoK5wNy" +
            "tv/35ry8Y1kRC64g5WV3/8YCZm8ePvvu84YRIah0xm/rLRA0Ek0AQ55fi/PJ6jAB7rRqDBIJ4aSleqmw" +
            "GgFNU3UpqIFip01O/GQERECcFQWnHsgmiIgEFoF26u0aeTRKfmQEmEpU7JNsdbJkqo7JPjb422Hc4jBY" +
            "AQ0SWysFU6pBsk7bQ2iIgD7TbHWOjr3Z37ckXrgFMpHLZoY+u/u7y7F/c8v/d1mB5oNPpGTv0Wkf7J5Y" +
            "K18AshJXLDE3/8533zryqAa/OVu2WKA/0egNjh76dy43kC9cBltLOZnZemf7N8YnvmopU2LZgeaA/+8D" +
            "Yodc9bzBfuA5ASiebGZy6/PaJ8z+galSoAYxAzCaIFnxgzZeXV75Fq1v6UYqtBwxEwHD7I58d/ZbjdBe" +
            "KMwCkdLOZgQuXfv7+xZ9IwElRdVw3mGEthNzRdyiIC2qt5uJyx/Hu4lSUFEunGQiAHq8/lx3ROqhw/cT" +
            "Entu3/1NfduzOYnEWgFKe5/adv/jWqUs/U+moagHT2hfCGX3sRTBjLTAlHWP0sZNfKSxOOStUeeDBrj2" +
            "HD7xkW+2J9ivdgLWUrjZx0b8JwFJZ1+2ZmHxz/PIvbcBOXSGu4R0jgI1JCLRmr12TNCYu7cAwQAF4qOf" +
            "xIwdfkcIOo7uVJyOB4rhgOAZgWznH7ho/9/2z0792AWs9de8ag0eFVJ1IGJMATCtUj/R/5siBbzBz0b+" +
            "ZsjXOzLbdbqvc38+9ce7qH9ZLhcZFRSKRACHwyR1PPvHYi9okYXgnNZWx7Q5Lee+fef38jT9lALX+HkV" +
            "DwIhEkvhF4MDQM6P7vpokfhgtpKdynC4prJPj37w4eyxbccNUBVUBIxJEsppPBJj71hSkdegHt/cOfO6" +
            "JfV8L48UoXrrvClShlcxsXKcH4OOnX5q6eaJmKlQGIxKu3e06XYKq5NGxDkreM+skKezZ/dzI0BfCeCG" +
            "K8ytUDAjH6RQky62sLCsTBHdOjL98ZX48u9Ixq01Ubnu6ASTJocEnlfIqhAoAkQ4HuvcO73w60YXlNQV" +
            "Ajt2RJH6ig3u0YCksz+3/6OrvZ+ZPW8JaMzYqKzM/PzG79KFbd9u77FBIgFlfmjla9ZnlgX0meOjBLyW" +
            "6uJJ4UBQvMvPKGBop3aw3cOnyr05O/iguv6xkQAFerTD3qyzYMk/Ke9hW+39/0/4z15iNkl4mMzD5wU9" +
            "PffCWBNo3ZWdgY5NgZmOpjOv2TVz48empX6wrdahTjax5sLFU1nW7z57/4fiVt51NpMKGgtHKAQBgY1t" +
            "ttt0xfu57Z6Z/660/dahTGwBmAEtlc9kHpHRKKaKUjtbBqbPf+ce1d2pLHepU2XCfXjHQ07ZroO9wkvg" +
            "l/5XKLCx+OH37lL0VVNgQMAGE921UWVYpcNe/FaU2bdBUBKwyZ7dqz/d2ryvWrBZYs6kF1mxqgTWb/g0" +
            "jofSwF3SV5QAAAABJRU5ErkJggg==")]
        public string TwitchPage3 {
            get {
                return ((string)(this["TwitchPage3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAIAAABoJHXvAAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAF0WlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOnhtcE1NPSJodHRwOi8" +
            "vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIiB4bWxuczpzdEV2dD0iaHR0cDovL25zLmFkb2JlLmNvbS9" +
            "4YXAvMS4wL3NUeXBlL1Jlc291cmNlRXZlbnQjIiB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2V" +
            "sZW1lbnRzLzEuMS8iIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3A" +
            "vMS4wLyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTAzLTI2VDAwOjM2OjA4LTA3OjAwIiB4bXA6TWV0YWRhdGFEYXRlPSI" +
            "yMDE5LTAzLTI2VDAwOjM2OjA4LTA3OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjAxOS0wMy0yNlQwMDozNjo" +
            "wOC0wNzowMCIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDoxZmIwZWZkZS1mMjhhLTBhNGMtOTZkNi0" +
            "wYTk2NjdjMTQxOGMiIHhtcE1NOkRvY3VtZW50SUQ9ImFkb2JlOmRvY2lkOnBob3Rvc2hvcDoxMzRjNjE" +
            "0My04YmEwLWU1NDUtYmQyYi1kMzFlNDY0NjE4MmMiIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1" +
            "wLmRpZDoyOTVmOTMwOC03ZWY5LWVkNGYtYmNhMy0yMTkxNzgyMzc1NmYiIGRjOmZvcm1hdD0iaW1hZ2U" +
            "vcG5nIiBwaG90b3Nob3A6Q29sb3JNb2RlPSIzIj4gPHhtcE1NOkhpc3Rvcnk+IDxyZGY6U2VxPiA8cmR" +
            "mOmxpIHN0RXZ0OmFjdGlvbj0iY3JlYXRlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDoyOTVmOTM" +
            "wOC03ZWY5LWVkNGYtYmNhMy0yMTkxNzgyMzc1NmYiIHN0RXZ0OndoZW49IjIwMTktMDMtMjZUMDA6MzY" +
            "6MDgtMDc6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5" +
            "kb3dzKSIvPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0ic2F2ZWQiIHN0RXZ0Omluc3RhbmNlSUQ9InhtcC5" +
            "paWQ6MWZiMGVmZGUtZjI4YS0wYTRjLTk2ZDYtMGE5NjY3YzE0MThjIiBzdEV2dDp3aGVuPSIyMDE5LTA" +
            "zLTI2VDAwOjM2OjA4LTA3OjAwIiBzdEV2dDpzb2Z0d2FyZUFnZW50PSJBZG9iZSBQaG90b3Nob3AgQ0M" +
            "gMjAxOSAoV2luZG93cykiIHN0RXZ0OmNoYW5nZWQ9Ii8iLz4gPC9yZGY6U2VxPiA8L3htcE1NOkhpc3R" +
            "vcnk+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5" +
            "kPSJyIj8+Z/pWLgAADDBJREFUeJztnW1sFMcZgHdn9/Z8vrPvzmeD8eGzmwTSHKXKQVMQqpofARKlhAp" +
            "UJKchEVGcUiBNUZVC0tRqI5oSEqmiCeQLV6BCBUlUkChEqNA2pZKTooITIixCUnDt+Dh/nM/2ne9zd6Y" +
            "/LiUOkNm9u5ndHTrPX6+94312Zt6dr1d8ds3HAocdgNUF4JQGF8YYXBhjcGGMwYUxBhfGGFwYY3BhjMG" +
            "FMQYXxhhcGGNwYYzBhTEGF8YYXBhjcGGMwYUxBhfGGFwYY3BhjMGFMQYXxhhcGGNwYYzBhTGGbHUBKiI" +
            "YkhYs9QRmON1eRa6SgCyKQBAEQRQBQhBBAUEBQaRmtVxGTcTyZ7tSPd15q0tdESJzS7WXrHB/daHX5VU" +
            "khyQCsdRfRxBpBS2fUi+enTh5NDUWhzQKSQ9mhK1s9950u8/hksuQ9GUU5UXPTxzZO8aKObsLC0eUpQ9" +
            "Mc/mdBD1dC4KokFE/+MvI8UOT9O5CBPsKW7LCHbm7QXaa2stqBXWgZ2Lf9lEzb1oSdhRmiaqpQBX2vj9" +
            "2YKcdtdlLWDii3PvIDMXtsLoggiAIWkH9x5uDXScyVhfkC9hI2KMd0+pba6j2VSUDUTqR27M1ap+QRLr" +
            "r9setLoMQjigP/7K5psElinayJQiCKDqq5fmLfS4pf/F8werSCIIdPpzbNtR9ZZ7fXhXriwAg3rGs8ZZ" +
            "5k690xKwui9VN4o+2NdVMq67kLyCIoKZpeZSbLKh5mE1pmZSWTqrVNbIgCDV1cpVHdrodkiICqZwP7ak" +
            "UMuqujj5rm0fLhPkCoP2Z5jLjC4jUgpYczn7w9/GSgoJwRFmw1Fvf4padZcrTCuq+X/UP9Gll/C4RrBH" +
            "mC4AfPBsqI3DXCupof/qtl0cqf81Xtntvnud3OCWhRHMQosM7+q0ak7RAWDAkre4ISbJUwu9AlM+ob//" +
            "uMvHHFAxJqx6fUepICoTo5P6oJRG/2cJ8AbD2uZYSbEGUTeWP7Rmk+kb7AuDBTY2eepdxbVbVM1PD+s9" +
            "aQsVoS6gV1JNvxN58OT4co9tnZDPo1InkaP/kzV93Sw5Dc4SiKM6+o3a0f5J22a7CVGGPvRByuIxFGRA" +
            "NX0q++NOB/osq5UJ9znBM6zo61tCg1c2sNvJFKIrirPmec10T2QwyoXhFzJtxXrel0WBMCFX4zv7ori1" +
            "DtIt0XQ52ju99plfNGXpRJFl6dEuIdpGmYpKw5Q/V+pvcRq4sZNRXn+y1dgRvoE97/oe9yaG0kYsdLnn" +
            "dlkbaRbqCGcKCIWnOnQ1Goud0PPvC+l6bDNy9tDl6+fy4APWbO3+Te8kKQ69j5Zgh7PtPNhuJvhKfprY" +
            "/8akJ5THO7m3DF88k9J0Bcf69030BMx4m9Xus3ljncOmHhcmhtB1G6q7lwM5RI86ADNY81WRCeegK8wV" +
            "A81y/7mXZidxLm6NUS1IJB3aODvcmdS+r9jsXLXbRLgxdYWueatJtDNWc+psf91MtRuXs2jKkH4MA8Vv" +
            "fm067JBSFhSNKtd+JvwZC9PrTffTKQJCXNkd1Y33ZKa9s91ItBkVh9z4yQycyhOj0kZhNYkIj/OHX/Ui" +
            "vM5u1oI5qGWgJC0cURS/WSI5k7L+sbCoDfdqlMwn8NZIsUa1ktITds2Y6vnpBiPY+b8ewEM+BnaOFjE7" +
            "DOOub+nFW2VAR5gsAp0fBX3PhXQJzWpZwdFcUH+VLDpleuEhF2Kr19fjgUCuoBzvHadzaBHq68+lEDn/" +
            "NwvvqKd2dirC6Zp1lGh+f0ukJbM5bL17GRx9Oj0Jp4IP8Hw1HFMmBCzc0VWO3ehUZ6NNyKdzUpQjEe9p" +
            "8NG5NXtidK3Xi2qFPUsRvaj7v/WkEf8HM22po3Je8sJqGKsxPEUSHOuPEb2o+XScymoqbazYygloGhIX" +
            "5AkB24NZrFDIqo8HhtUzEcJN2IhBpzLkQFvbt73jwn18X3x8je0cLObxrGH/BLfPIt4qEhbXM8eB+DNF" +
            "fD+kPe7PCQJ8GVVxr4QngeofyICysqgb3vaxp2g3THhbJp3E7JCRnKWsvjUFYGH6NWDrB9g7+a4lewI2" +
            "FAkEg/jVG+s9hO7DhvizZ21nO2S7sJwoQwxGdCaZSISksHFHwEYfOv8cgPd15/JBH6FbCg4okhQVbscs" +
            "OIWL9UJPrghfmb9QZBC8VksICTbjqf0MFG1OAGu4/kxUb92EuD/mgyP4g7JvoqCL8TEgKkxVcB4bgjVn" +
            "H8E0ikGxcw/DVH2nm7RgwE3yTSBx+/B5jkBSm5nHvmvh/+W4Qr39kheEaPfEGNSZhZyeIQ/Ihjsd1JmE" +
            "J3ss+4N/DQpbw/kySwmK9OsLM2d9hMgBbw7IpwjtIST7Bnm6dtUTEB9bsAP4JDv6H8PApSWFjcYj/KLl" +
            "1Pna2jEEWLXbhh09Pv0N4aTPhNgpquCbb30R+Qs9a8K8ggoj4mTmEhWnYQFGptsVBiAQJYFdg4l/f8iA" +
            "sbHwQty4FyCAYuqHGG2Xs0qhCxvbCzr2rs2Rj6f10d+OYyaLFLvyEbSJKfsKWsLCuExl83DHtZpN225u" +
            "A7gL6f/6Z/AJn8h9G+N04kkMORwjP6VkFfocOVCGNCVvywmKf6LSKd7XR2tlhJm0b6vBjN9lxKtPr5IU" +
            "d2TuGbxU99a4bYMgjNLcWf8GpY1RWpJN/cGNxqOZw0ZEIxPs3TiN+XzNZssKNP50TqpDS6UtU3vSP3tM" +
            "5ot/X5Ga6kkXubsBfMB4zdE5VGVB5aod/P4FfwywC8cFN5h2oRZa2DXU6h99CpLvsvmxoveaDeqFHTb2" +
            "LxXDRFwCt83T2nGdTeXqnONMStnvbMMQfaQHEZWvNOJyJLGueasJ/LAsQHdszSK8AFDuSuN75TLLT1JM" +
            "GK2f5Q7W6Z/tkU3mq62UpCnvr5RGdSmbuSYMVEgxJYd1THylXL4GqsLE4/PRDvdMCgDh/WaP9OzNfAKz" +
            "+ebNOYygI6USO9nJ0urH1vu2jugdqASAuXz/T5lF++zPN+KMRBEGAEO3ZSv0QQeqP6chrOufGCIIAZLB" +
            "2a8i2zn7yW0MpR3rPJEzYrkj9GfV05xNR/WlyySGv3Rqy4WzZEztaqmr1l6IUMqo5Gf3MeKlf6YgZOVV" +
            "ccsgPdrTYpz/zBcCmV1uN1C0I0a4Ok059NKkVOvJaVDdiFAQByGD5Y812iBvDEWXtcy2G0vmYe+qjSZk" +
            "hhmOaS8oHZ3kEvYwLoigGZ3m+dofzX3+zbLtm24a6hd+dbnDjyeWPJv7YOUa5RJ9jXj9//NBkn26UXwS" +
            "I/pmeTa+2mt88BkPSEztabvqGzlzXFZJD6d3baA0bXhezsxut29Lon2l4daK5OUNLzZpayKgvrO+lWaL" +
            "rYEH+sFLTKEKI4r1JIknevoy2DXUtt3tLSmmm5tTXn7YgvaI1GfrKSH0JIZocyRzcOUhwINwXAKvW1wd" +
            "CHiCX1jVYZUuwMAdmaW3jFSBSC9rwpclDnfGyn5cvAO5p8828rcbhksvYU5OfLHT+ot+qI32szDK7emN" +
            "daK6/1BSUnwGRpmm5CTV2KX22K6U7ghcMSQuWeoKz3C6vIjnKTzebHEpbm8TC4rTAS1a45y9r1B1U1QV" +
            "BhCBCCCL4hW39IhCABEQgVr47DUHU/2Fi33YzhjMwWJx4+/ihyZ7TvQ/8rLmMjLNT+Z8SWl8pUIUn37h" +
            "sbVazItaPtxazqw1fnNBNumANEKXjWctz0F3B4iZxKuGIsmxtU4VVjSxQhaffHrRV+gobCSuyst07e0G" +
            "g1DibOAiikd6kVXk4MdhOWJGHNzdMn11beTBSBgii1Ehm7/M2zeJjU2FFVm+sC84pbQCiEiBE49HJ/du" +
            "H7KmqiI06jGvZt31UEEYXLXYtvK/e6VEoHRyBIFJz2r/PJJhIf2DrGnYVK9u9rXNrFY9CpKkserp8YeL" +
            "I3jE7V6mrsHUNu4qDneOCMC4IQjiiLFjq9TdVOVwSkIwOWyCIIIRaDo4PZs69m7RJmF4qLAm7Qk93vqf" +
            "781koXwCEI87GVsUbUKqmnNmYTWmFnJZOacm42nM6S2/5tJkwKewqxuLFvT1M1phSsX6kg1MSXBhjcGG" +
            "MwYUxBhfGGFwYY3BhjMGFMQYXxhhcGGNwYYzBhTEGF8YYXBhjcGGMwYUxBhfGGFwYY3BhjMGFMQYXxhh" +
            "cGGNwYYzBhTEGF8YY/wXESZjrh7tSTQAAAABJRU5ErkJggg==")]
        public string TwitchNotLive {
            get {
                return ((string)(this["TwitchNotLive"]));
            }
        }
    }
}
